@baseUrl = https://localhost:5001/messenger/

POST {{baseUrl}}users/register
Content-Type: application/json

{
    "userName": "Bulisz",
    "password": "123456",
    "confirmPassword": "123456",
    "email": "bulisz@freemail.hu"
}

###

POST {{baseUrl}}users/login
Content-Type: application/json

{
    "userName": "Bulisz",
    "password": "123456"
}

###

GET {{baseUrl}}users/getcurrentuser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZDMzNDdiNC0zOGI2LTQzMzctOTA5MC0yMzkzYTk1OWRkNzMiLCJqdGkiOiIxOGUzYzM2Yy1jZjg4LTRiNjEtOGEzMS0wYjkxZDAzNWUwMzciLCJpYXQiOiIyMDIzLiAwNy4gMDUuIDc6NDQ6NDMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjlkMzM0N2I0LTM4YjYtNDMzNy05MDkwLTIzOTNhOTU5ZGQ3MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJCdWxpc3oiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJidWxpc3pAZnJlZW1haWwuaHUiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNjg4NTQzMTQzLCJpc3MiOiJwcm9nbWFzdGVycy5odSIsImF1ZCI6InByb2dtYXN0ZXJzLmh1In0.6DfG2bdS3XMAT9ASuGDr4z8f4ofRKtIAM_4vTYK_VQk

###

POST {{baseUrl}}users/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZDMzNDdiNC0zOGI2LTQzMzctOTA5MC0yMzkzYTk1OWRkNzMiLCJqdGkiOiIxOGQ0NDk0Ni0xOWNjLTQzYTEtYmZmYS1mNzEwODUyNGZiYzIiLCJpYXQiOiIyMDIzLiAwNy4gMDUuIDc6NTI6NDMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjlkMzM0N2I0LTM4YjYtNDMzNy05MDkwLTIzOTNhOTU5ZGQ3MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJCdWxpc3oiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJidWxpc3pAZnJlZW1haWwuaHUiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNjg4NTQzNjIzLCJpc3MiOiJwcm9nbWFzdGVycy5odSIsImF1ZCI6InByb2dtYXN0ZXJzLmh1In0.qIEJso6KHWOyn80AN3NoOhJD8o8g90Tina5ijceE8SE
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZDMzNDdiNC0zOGI2LTQzMzctOTA5MC0yMzkzYTk1OWRkNzMiLCJleHAiOjE2ODg1NDQxNjMsImlzcyI6InByb2dtYXN0ZXJzLmh1IiwiYXVkIjoicHJvZ21hc3RlcnMuaHUifQ.hanWkiavGFpmu9Hl1nefiSD3lh_b809l4QG43BC8afA"
}

###

POST {{baseUrl}}users/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZDMzNDdiNC0zOGI2LTQzMzctOTA5MC0yMzkzYTk1OWRkNzMiLCJqdGkiOiIyYjk5OTY3YS1lNjVhLTRmYzgtYmQyZS0zOGVlNGVhNTFkNTQiLCJpYXQiOiIyMDIzLiAwNy4gMDUuIDc6NTU6NTgiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjlkMzM0N2I0LTM4YjYtNDMzNy05MDkwLTIzOTNhOTU5ZGQ3MyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJCdWxpc3oiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJidWxpc3pAZnJlZW1haWwuaHUiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNjg4NTQzODE4LCJpc3MiOiJwcm9nbWFzdGVycy5odSIsImF1ZCI6InByb2dtYXN0ZXJzLmh1In0.3bsYx7swp-hFzQcrP7aSsVt-Zuyr3Z1wN7OOrpSMr_A
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZDMzNDdiNC0zOGI2LTQzMzctOTA5MC0yMzkzYTk1OWRkNzMiLCJleHAiOjE2ODg1NDQzNTgsImlzcyI6InByb2dtYXN0ZXJzLmh1IiwiYXVkIjoicHJvZ21hc3RlcnMuaHUifQ.wWbX_GwO-QeKh5BXbb1DGobmT7wRiwzue675MMUwOBc"
}


